$ python nornir_jinja.py
--Return--
None
> /home/carl/nornir_j2/nornir_jinja.py(14)main()
     13     nr = nr.filter(name="srx2")
---> 14     import ipdb; ipdb.set_trace()
     15

ipdb> TEMPLATE_STR
'interface loopback{{ int_num }}\n  description {{ descr | reverse }}\n  no shut'
ipdb> result = nr.run(task=text.template_string, template=TEMPLATE_STR, int_num="1234", descr="loopy")
ipdb> result
AggregatedResult (template_string): {'srx2': MultiResult: [Result: "template_string"]}
ipdb> result["srx2"][0].result
'interface loopback1234\n  description ypool\n  no shut'
ipdb> result = nr.run(task=text.template_file, template="interfaces.j2", path=".")
Host 'srx2': task 'template_file' failed with traceback:
Traceback (most recent call last):
  File "/home/carl/VENV/py3_venv/local/lib/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/home/carl/VENV/py3_venv/local/lib/python3.6/site-packages/nornir/plugins/tasks/text/template_file.py", line 35, in template_file
    **kwargs
  File "/home/carl/VENV/py3_venv/local/lib/python3.6/site-packages/nornir/core/helpers/jinja_helper.py", line 18, in render_from_file
    return t.render(**kwargs)
  File "/home/carl/VENV/py3_venv/local/lib64/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/carl/VENV/py3_venv/local/lib64/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/carl/VENV/py3_venv/local/lib64/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/carl/VENV/py3_venv/local/lib64/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "./interfaces.j2", line 1, in top-level template code
    {% for interface, data in interfaces.items() %}
  File "/home/carl/VENV/py3_venv/local/lib64/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'interfaces' is undefined

ipdb>
